// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WcsEvents.Sync.Data;

#nullable disable

namespace WcsEvents.Sync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WcsEvents.Sync.Data.CrawlState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighestFoundWscid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastAttemptedWscid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFullCrawlCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastScoringSyncUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CrawlStates");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.Dancer", b =>
                {
                    b.Property<int>("Wscid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCrawledUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Wscid");

                    b.HasIndex("LastCrawledUtc");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Dancers");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.Division", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "JRS",
                            Name = "Juniors"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "MSTR",
                            Name = "Masters"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NEW",
                            Name = "Newcomer",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NOV",
                            Name = "Novice",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "INT",
                            Name = "Intermediate",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "ADV",
                            Name = "Advanced",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "CHMP",
                            Name = "Champions",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "ALS",
                            Name = "All-Stars",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "INV",
                            Name = "Invitational"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "PRO",
                            Name = "Professional"
                        });
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.JudgeMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Judge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Placement")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Points")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("Judge");

                    b.ToTable("JudgeMarks");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.Placement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DancerWscid")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DivisionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DancerWscid");

                    b.HasIndex("DivisionId", "Role", "DancerWscid");

                    b.HasIndex("EventId", "DateRaw", "DivisionId", "Role");

                    b.ToTable("Placements");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.PublishedDoc", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Path");

                    b.ToTable("PublishedDocs");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Advanced")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bib")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlternate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsScratched")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LinkedByMatch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Score")
                        .HasColumnType("TEXT");

                    b.Property<int>("TableIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Wscid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Wscid");

                    b.HasIndex("RoundId", "TableIndex");

                    b.ToTable("ScoringEntries");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringEvent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWsdc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateFrom");

                    b.ToTable("ScoringEvents");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringRound", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionAbbreviation")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsJackAndJill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoringEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScoringEventId");

                    b.HasIndex("DivisionAbbreviation", "IsJackAndJill", "Kind");

                    b.ToTable("ScoringRounds");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.JudgeMark", b =>
                {
                    b.HasOne("WcsEvents.Sync.Data.ScoringEntry", "Entry")
                        .WithMany("Marks")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.Placement", b =>
                {
                    b.HasOne("WcsEvents.Sync.Data.Dancer", "Dancer")
                        .WithMany("Placements")
                        .HasForeignKey("DancerWscid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WcsEvents.Sync.Data.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dancer");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringEntry", b =>
                {
                    b.HasOne("WcsEvents.Sync.Data.ScoringRound", "Round")
                        .WithMany("Entries")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.Dancer", b =>
                {
                    b.Navigation("Placements");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringEntry", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("WcsEvents.Sync.Data.ScoringRound", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
